apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- persistentvolumeclaim.yaml
- postgres-config.yaml
- postgres.yaml
- random_wiki-cronjob.yaml
- todo_app-deployment.yaml
- todo_app-service.yaml
- todo_backend-deployment.yaml
- todo_backend-service.yaml
- broadcaster-deployment.yaml
- gateway.yaml
- routes.yaml
