apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: project
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "postgres"
  POSTGRES_HOST: "postgres-svc"
  POSTGRES_PORT: "5432"
