apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}
        - name: ping-pong-volume
          persistentVolumeClaim:
            claimName: ping-pong-pv-claim
      containers:
        - name: log-output-generator
          image: hanseni/log_output:1.10-generator
          env:
            - name: FILE
              value: "/shared/log.txt"
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
        - name: log-output-server
          image: hanseni/log_output:1.11-server
          env:
            - name: PORT
              value: "3000"
            - name: FILE
              value: "/shared/log.txt"
            - name: PING_PONG_FILE
              value: "/pingpong/pingpong.txt"
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
            - name: ping-pong-volume
              mountPath: /pingpong