apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: ping-pong-volume
          persistentVolumeClaim:
            claimName: ping-pong-pv-claim
      containers:
        - name: ping-pong
          image: hanseni/ping_pong:1.11
          env:
            - name: PORT
              value: "3000"
            - name: FILE
              value: "/pingpong/pingpong.txt"
          volumeMounts:
            - name: ping-pong-volume
              mountPath: /pingpong