apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/haensen/kubernetes-submissions
    path: project/base/overlays/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true