apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: staging
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: NATS_URL
              value: "nats://nats-staging:4222"
