apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
spec:
  template:
    spec:
      containers:
        - name: todo-backend
          env:
            - name: NATS_URL
              value: "nats://nats-staging:4222"
