apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: html
          emptyDir: {}
      containers:
      - name: nginx
        image: nginx:1.29
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
      initContainers:
      - name: init-container
        image: hanseni/wiki-init:5.4
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
      - name: sidecar
        image: hanseni/wiki-sidecar:5.4-2
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
        restartPolicy: Always