apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-rate
  namespace: exercises
spec:
  metrics:
  - name: cpu-rate
    initialDelay: 5m
    successCondition: "all(result, # < 0.15)" # 0.001 makes the rollout fail
    provider:
      prometheus:
        address: http://kube-prometheus-kube-prome-prometheus.prometheus.svc.cluster.local:9090
        query: scalar(sum(rate(container_cpu_usage_seconds_total{namespace="exercises"}[30s])))
        rangeQuery:
          start: 'now()-duration("5m")'
          end: 'now()'
          step: 1s