apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: log-output-config
            items:
              - key: FILE_CONTENT
                path: information.txt
      containers:
        - name: log-output-generator
          image: hanseni/log_output:1.10-generator
          env:
            - name: FILE
              value: "/shared/log.txt"
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
        - name: log-output-server
          image: hanseni/log_output:2.5-server
          env:
            - name: PORT
              value: "3000"
            - name: FILE
              value: "/shared/log.txt"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts:
            - name: shared-volume
              mountPath: /shared
            - name: config-volume
              mountPath: /config
              readOnly: true