apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ping-pong-rollout
  namespace: exercises
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ping-pong
  strategy:
    canary:
      analysis:
        templates:
        - templateName: cpu-rate
      steps:
        - setWeight: 33
        - pause:
            duration: 1m
        - setWeight: 66
        - pause:
            duration: 5m
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: hanseni/ping_pong:4.1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          env:
            - name: PORT
              value: "3000"
            - name: PGHOST
              value: "postgres-svc"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: "password"
            - name: PGDATABASE
              value: "postgres"
            - name: TEST_VALUE_TO_TRIGGER_ROLLOUT
              value: "0e"