apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/postgres-config.yaml
- manifests/postgres.yaml
- manifests/db_backup-cronjob.yaml
- manifests/random_wiki-cronjob.yaml
- manifests/todo_app-deployment.yaml
- manifests/todo_app-service.yaml
- manifests/todo_backend-deployment.yaml
- manifests/todo_backend-service.yaml
- manifests/broadcaster-deployment.yaml
- manifests/gateway.yaml
- manifests/routes.yaml
images:
- name: BROADCASTER-IMAGE
  newName: hanseni/broadcaster
  newTag: 8b45cc17c064aaa2c3c0e5023458066758a23cfc
- name: DB-BACKUP-IMAGE
  newName: hanseni/db_backup
  newTag: 8b45cc17c064aaa2c3c0e5023458066758a23cfc
- name: RANDOM-WIKI-TODO-IMAGE
  newName: hanseni/random_wiki_todo
  newTag: 8b45cc17c064aaa2c3c0e5023458066758a23cfc
- name: TODO-APP-IMAGE
  newName: hanseni/todo_app
  newTag: 8b45cc17c064aaa2c3c0e5023458066758a23cfc
- name: TODO-BACKEND-IMAGE
  newName: hanseni/todo_backend
  newTag: 8b45cc17c064aaa2c3c0e5023458066758a23cfc
namespace: project
