apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/postgres-config.yaml
  - manifests/postgres.yaml
  - manifests/random_wiki-cronjob.yaml
  - manifests/todo_app-deployment.yaml
  - manifests/todo_app-service.yaml
  - manifests/todo_backend-deployment.yaml
  - manifests/todo_backend-service.yaml
  - manifests/ingress.yaml