apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/analysistemplate.yaml
- manifests/log-output-rollout.yaml
- manifests/log-output-service.yaml
- manifests/ping-pong-rollout.yaml
- manifests/ping-pong-service.yaml
- manifests/postgres.yaml
- manifests/gateway.yaml
- manifests/routes.yaml
images:
- name: LOG-OUTPUT-GENERATOR-IMAGE
  newName: hanseni/log_output_generator
  newTag: dc3f84f94bf82d84caf49e7f4a59da0366676b27
- name: LOG-OUTPUT-SERVER-IMAGE
  newName: hanseni/log_output_server
  newTag: dc3f84f94bf82d84caf49e7f4a59da0366676b27
- name: PING-PONG-IMAGE
  newName: hanseni/ping_pong
  newTag: dc3f84f94bf82d84caf49e7f4a59da0366676b27
namespace: exercises
