apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/analysistemplate.yaml
- manifests/log-output-rollout.yaml
- manifests/log-output-service.yaml
- manifests/ping-pong-rollout.yaml
- manifests/ping-pong-service.yaml
- manifests/postgres.yaml
- manifests/gateway.yaml
- manifests/routes.yaml
- manifests/greeter-deployments.yaml
- manifests/greeter-services.yaml
- manifests/greeter-gateway.yaml
images:
- name: GREETER-IMAGE
  newName: hanseni/greeter
  newTag: "5.3"
- name: LOG-OUTPUT-GENERATOR-IMAGE
  newName: hanseni/log_output_generator
  newTag: fb01af828484d94d5c83dc6723a14371c3ea9ad3
- name: LOG-OUTPUT-SERVER-IMAGE
  newName: hanseni/log_output_server
  newTag: fb01af828484d94d5c83dc6723a14371c3ea9ad3
- name: PING-PONG-IMAGE
  newName: hanseni/ping_pong
  newTag: fb01af828484d94d5c83dc6723a14371c3ea9ad3
namespace: exercises
