apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/configmap.yaml
- manifests/postgres.yaml
- manifests/log-output-knative.yaml
- manifests/ping-pong-knative.yaml
- manifests/greeter-knative.yaml
images:
- name: GREETER-IMAGE
  newName: hanseni/greeter
  newTag: "5.3"
- name: LOG-OUTPUT-GENERATOR-IMAGE
  newName: hanseni/log_output_generator
  newTag: fb01af828484d94d5c83dc6723a14371c3ea9ad3
- name: LOG-OUTPUT-SERVER-IMAGE
  newName: hanseni/log_output_server
  newTag: "5.7"
- name: PING-PONG-IMAGE
  newName: hanseni/ping_pong
  newTag: fb01af828484d94d5c83dc6723a14371c3ea9ad3
