apiVersion: batch/v1
kind: CronJob
metadata:
  name: random-wiki-todo
  namespace: project
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: random-wiki-todo
            image: RANDOM-WIKI-TODO-IMAGE
            env:
            - name: TODO_POST_URL
              value: "http://todo-backend-svc:2345/todos"
          restartPolicy: OnFailure
