apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: TODO-APP-IMAGE
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi
          env:
            - name: PORT
              value: "3000"
            - name: IMAGE_PATH
              value: "/images"
            - name: FETCH_TIME_INTERVAL_MINUTES
              value: "10"
            - name: PICSUM_PHOTOS_URL
              value: "https://picsum.photos/600"
          volumeMounts:
            - name: image-volume
              mountPath: /images
      volumes:
        - name: image-volume
          persistentVolumeClaim:
            claimName: image-pv-claim
