apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: project
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: sa-volume
              secret:
                secretName: db-backup-sa
                items:
                  - key: credentials.json
                    path: credentials.json
          containers:
          - name: db-backup
            image: DB-BACKUP-IMAGE
            resources:
              requests:
                cpu: 200m
                memory: 100Mi
              limits:
                cpu: 500m
                memory: 200Mi
            env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
            - name: BUCKET_NAME
              value: "backup-bucket-56156"
            volumeMounts:
              - name: sa-volume
                mountPath: /creds
                readOnly: true
          restartPolicy: Never
