apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-deployment
spec:
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          env:
            - name: NATS_URL
              value: "nats://nats-production:4222"
            - name: WEBHOOK_URL
              value: "url_to_the_webhook"
