name: Release exercises

on:
  push:
    branches:
      - "**"
    paths:
      - "!exercises/kustomization.yaml"
      - "exercises/**"
      - ".github/workflows/cicd-exercises.yaml"
    tags:
      - "!**" # Don't trigger on releases

env:
  LOG_OUTPUT_GENERATOR: log_output/generator
  LOG_OUTPUT_SERVER: log_output/server
  PING_PONG: ping_pong
  NAMESPACE: exercises

jobs:
  build-log-output-generator-image:
    name: Build log output generator
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image_tag.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name : 'Form the image name 1'
        run: echo "IMAGE_TAG1=hanseni/log_output_generator:$GITHUB_SHA" >> $GITHUB_ENV
      - name: Build 1
        run: docker build --tag $IMAGE_TAG1 exercises/$LOG_OUTPUT_GENERATOR/.
      - name: Publish 1
        run: docker push $IMAGE_TAG1
      - name: Output the image tag
        id: image_tag
        run: echo "image_tag=$IMAGE_TAG1" >> $GITHUB_OUTPUT

  build-log-output-server-image:
    name: Build log output server
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image_tag.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name : 'Form the image name 2'
        run: echo "IMAGE_TAG2=hanseni/log_output_server:$GITHUB_SHA" >> $GITHUB_ENV
      - name: Build 2
        run: docker build --tag $IMAGE_TAG2 exercises/$LOG_OUTPUT_SERVER/.
      - name: Publish 2
        run: docker push $IMAGE_TAG2
      - name: Output the image tag
        id: image_tag
        run: echo "image_tag=$IMAGE_TAG2" >> $GITHUB_OUTPUT

  build-ping-pong-image:
    name: Build ping pong
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image_tag.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name : 'Form the image name 3'
        run: echo "IMAGE_TAG3=hanseni/ping_pong:$GITHUB_SHA" >> $GITHUB_ENV
      - name: Build 3
        run: docker build --tag $IMAGE_TAG3 exercises/$PING_PONG/.
      - name: Publish 3
        run: docker push $IMAGE_TAG3
      - name: Output the image tag
        id: image_tag
        run: echo "image_tag=$IMAGE_TAG3" >> $GITHUB_OUTPUT

  update-kustomization-yaml:
    name: Update kustomization to use the new images
    runs-on: ubuntu-latest
    needs: [build-log-output-generator-image, build-log-output-server-image, build-ping-pong-image]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Edit kustomization.yaml to use the new images
        env:
          IMAGE_TAG1: ${{ needs.build-log-output-generator-image.outputs.image_tag }}
          IMAGE_TAG2: ${{ needs.build-log-output-server-image.outputs.image_tag }}
          IMAGE_TAG3: ${{ needs.build-ping-pong-image.outputs.image_tag }}
        run: |-
          cd exercises
          kustomize edit set namespace $NAMESPACE
          kustomize edit set image LOG-OUTPUT-GENERATOR-IMAGE=$IMAGE_TAG1
          kustomize edit set image LOG-OUTPUT-SERVER-IMAGE=$IMAGE_TAG2
          kustomize edit set image PING-PONG-IMAGE=$IMAGE_TAG3

      - name: Commit edited kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'exercises/kustomization.yaml'
          message: kustomization.yaml updated to use the new images from ${{ github.sha }}