name: Delete namespace when branch is deleted

on:
  delete:
    branches:
      - "**"
    tags:
      - "!**" # Don't trigger on releases

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BRANCH: ${{ github.ref_name }}

jobs:
  delete-namespace:
    name: Delete namespace
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: google-github-actions/setup-gcloud@v2

      - name: 'Use gcloud CLI'
        run: gcloud info

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          project_id: '${{ env.PROJECT_ID }}'
          location: '${{ env.GKE_ZONE }}'

      - name: 'Get namespace name'
        run: |-
          if [ "${GITHUB_REF#refs/heads/}" == "main" ]; then
            echo "NAMESPACE=project" >> $GITHUB_ENV;
          else
            echo "NAMESPACE=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV;
          fi

      - name: Delete namespace
        run: kubectl delete namespace $NAMESPACE || true